
driver:
  name: ec2
  aws_ssh_key_id: JasonOregonKeyPair
  region: us-west-2
  availability_zone: us-west-2c
  require_chef_omnibus: true
  security_group_ids: sg-016f977a
  subnet_id: subnet-c1a95299
  associate_public_ip: true
  interface: dns
  retryable_tries: 120

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    driver:
      name: vagrant
  - name: amazon
    driver:
      image_id: ami-d2c924b2
    transport:
      username: centos
      ssh_key: ~/keys/JasonOregonKeyPair.pem
  - name: amazon_linux
    driver:
      image_id: ami-d2c924b2
    transport:
      username: ec2-user
      ssh_key: ~/keys/JasonOregonKeyPair.pem

suites:
  - name: default
    run_list:
      - recipe[chef-centos7-common::default]
      - recipe[chef-centos7-common::export-node]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
