source 'https://supermarket.chef.io'

metadata

cookbook 'chef-centos7-common', "~> 0.1.0", github: "jasondebolt/chef-centos7-common", branch: "master"
cookbook 'chef-centos7-httpd', "~> 0.1.0", github: "jasondebolt/chef-centos7-httpd", branch: "master"
